server:
  compression:
    # enable response compression
    enabled: true

    # mime-types that should be compressed (wildcards NOT supported)
    mime-types: "application/javascript, application/json, application/xml, application/x-yaml, application/x-protobuf, application/x-protostuff, text/css, text/html, text/javascript, text/plain, text/xml,  text/x-yaml, text/yaml"

    # response size at which compression kicks in
    min-response-size: 4KB
